export default class Professor
{
    constructor()
    {
        this.matrix = [
            ["SYNTACTIC", 'DESCRIPTION'],
            ["SY#1", 'Use of "in order to" in negative sentences.'],
            ["SY#2", 'Use "ing" like a noun or as part of a "noun.'],
            ["SY#3", 'Use of "ing" after prepositions.'],
            ["SY#4", 'Agreement: conjugation/subject pronouns.'],
            ["SY#5", 'Spelling problem'],
            ["SY#6", 'Appropriate demonstrative.'],
            ["SY#7", 'Parallel structure.'],
            ["SY#8", 'Use of semicolon.'],
            ["SY#9", 'Use of question and exclamation mark.'],
            ["SY#10", 'Indentation.'],
            ["SY#11", 'Use "it" to complement the sentence.'],
            ["SY#12", 'Use of article "the".'],
            ["SY#13", 'Use of "of".'],
            ["SY#14", 'Use of "in".'],
            ["SY#15", 'A rule for developing a thesis statement.'],
            ["SY#16", 'Rules for doing a conclusion.'],
            ["SY#17", 'Rules to cite.'],
            ["SY#18", 'Correct preposition.'],
            ["SY#19", 'Do not use quotation marks.'],
            ["SY#20", 'Use of quotation marks.'],
            ["SY#21", 'Use of adjectives in plural nouns.'],
            ["SY#22", 'Use of adjectives within a sentence.'],
            ["SY#23", 'Use of "agree"/"agreement.'],
            ["SY#24", 'Use of the expression "most of the people".'],
            ["SY#25", 'Use of "because"/"because of".'],
            ["SY#26", 'Plural forms.'],
            ["SY#27", 'Missing complement.'],
            ["SY#28", 'Advice.'],
            ["SY#29", 'Expressing possession.'],
            ["SY#30", 'long sentences.'],
            ["SY#31", 'Commas.'],
            ["SY#32", 'Topic sentence.'],
            ["SY#33", 'Word order.'],
            ["SY#34", 'Paragraph.'],
            ["SY#35", 'Relative clauses.'],
            ["SY#36", 'Everybody, nobody.'],
            ["SY#37", 'Synonyms (not redundancy).'],
            ["SY#38", 'Colon.'],
            ["SY#39", 'Omit.'],
            ["SY#40", 'Capitalization.'],
            ["SY#41", 'Period at the end of a sentence.'],
            ["SY#42", 'Missing word.'],
            ["SY#43", 'Do not put period to your title.'],
            ["SY#44", 'Use of etc.'],
            ["SY#45", 'Wrong subject in the dependent clause.'],
            ["SY#46", 'Wrong use of tenses.'],
            ["SY#47", 'Not conjugation of verbs when using modals.'],
            ["SY#48", 'Use of "to" with modals.'],
            ["SY#49", 'Use of indefinite articles.'],
            ["SY#50", 'Difference between definite and indefinite articles.'],
            ["SY#51", '"there" before "exist".'],
            ["SY#52", 'Superlatives and comparatives.'],

            ["PRAGMATIC", 'DESCRIPTION'],
            ["P#1", 'Contractions.'],
            ["P#2", 'Title.'],
            ["P#3", 'Level of formality.'],
            ["P#4", 'Correct person according to the type of text.'],
            ["P#5", 'Expository text.'],

            ["SEMANTIC", 'DESCRIPTION'],
            ["S#1", 'Resembles spanish but differs in meaning.'],
            ["S#2", 'Use of synonyms.'],
            ["S#3", 'Redundancy in meaning.'],
            ["S#4", 'Use of connectors.'],
            ["S#5", 'Correct prefix.'],
            ["S#6", 'Correct suffix.'],
            ["S#7", 'Use of "ed"/"ing" in adjectives.'],
            ["S#8", 'Use of "another"/"other".'],
            ["S#9", 'Coherence.'],
            ["S#10", 'Phrasal verbs.'],
        ];
    }

    getMatrix = () =>
    {
        return this.matrix;
    }
}